config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "spaceships#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # # root "articles#index"
  # get "my_spacehips", to: "spaceships#my_spaceships"
  get "profile", to: "pages#profile"
  resources :users, except: [:index]
  resources :spaceships do
    resources :reservations, except: [:index, :edit, :update]
      collection do
        get :my_spaceships
        get :my_bookings
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    if end_date < start_date
      errors.add(:end_date, 'must be after the start date.')
    end
  end

  # def end_date_after_start_date
  #   return if end_date.blank? || start_date.blank?

  #   if end_date < start_date
  #     errors.add(:end_date, "must be after the start date")
  #   end
  # end
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :category, presence: true, inclusion: { in: ["A", "B", "C", "D", "E"] }
  validates :location, presence: true
  validates :price, presence: true
  validates :description, length: { minimum: 15 }
  validates :speed_of_light, presence: true
  validates :capacity, presence: true
  validates :fuel_drive, presence: true
  validates :brand, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :space_driving_license, presence: true, uniqueness: true

  has_many :spaceships
  has_many :reservations
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :space_driving_license])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :space_driving_license])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def create
    flash[:alert] = "Please login first" unless current_user
    @spaceship = Spaceship.find(params[:spaceship_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.spaceship = @spaceship
    @reservation.user = current_user
    if @reservation.save
      redirect_to spaceship_reservation_path(@spaceship, @reservation)
    else
      render "spaceships/show", status: :unprocessable_entity
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @spaceship = Spaceship.find(params[:spaceship_id])
    @reservation.spaceship = @spaceship
    @reservation.user = current_user
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @spaceship = Spaceship.find(params[:spaceship_id])

    @reservation.destroy
    redirect_to spaceship_path, status: :see_other
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end



end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @spaceships = Spaceship.search_by_name_and_description(params[:query])
    else
      @spaceships = Spaceship.all
    end
  end

  def show
    @spaceship = Spaceship.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @spaceship = Spaceship.new
  end

  def my_spaceships
    @spaceships = Spaceship.all.where(user: current_user)
  end

  def my_bookings
    @reservations = Reservation.all.where(user: current_user)
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    if @spaceship.save
      redirect_to spaceship_path(@spaceship)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @spaceship = Spaceship.find(params[:id])
  end

  def update
    @spaceship = Spaceship.find(params[:id])
    if @spaceship.update(spaceship_params)
      redirect_to spaceship_path(@spaceship)
    else
      render :new
    end
  end

  def destroy
    @spaceship = Spaceship.find(params[:id])
    @spaceship.destroy
    redirect_to spaceship_path(@spaceship), status: :see_other
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :category, :location, :price, :description, :speed_of_light, :capacity, :fuel_drive, :brand, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orbitat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

      <div class="container-fluid">

        <div id="logo-1">
          <%= link_to root_path, class: "navbar-brand" do %>
            <div id="logo">
              <h1 id="o">orbit</h1>
              <h1 id="at">@</h1>
            </div>
          <% end %>
        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="searchbar">
          <%= form_with url: spaceships_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a spaceship"%>
          <% end %>

          <%# <%= simple_form_for :search, url: root_path, method: :get do |f| %>
            <%# <div class="search-form-control form-group"> %>
              <%# <input class="form-control string required" type="text" name="search[query]" id="search_query" /> %>
              <%# <button name="button" type="submit" class="btn btn-flat"> %>
                <%# <i class="fas fa-search"></i> %>
              <%# </button> %>
            <%# </div> %>
          <%# <% end %>

        </div>

        <div id="add-spaceship">
          <%= link_to "add your spaceship", new_spaceship_path, class: "nav-link" %>
        </div>

        <div class="dropdown">
          <div class="avatar"></div >
          <div class="dropdown-content">
          <% if user_signed_in? %>
          <p><%=link_to "Profile", profile_path, class: "dropdown-text"%></p>
          <p><%=link_to "Log out", destroy_user_session_path, class: "dropdown-text", data: {turbo_method: :delete}%></p>
          <%else%>
          <p><%=link_to "Log in", new_user_session_path, class: "dropdown-text" %></p>
          <%end%>
          </div>
        </div>

      </div>
    </div>

    <%= render "shared/flashes" %>

    <%= yield %>

    <div class="footer">
      <div class="footer-content">
        <ul class="footer-list-left">

          <%date = Date.today%>
          <li class="footer-text">©<%= date.year  %>, Orbitat Inc.</li>
          <li><%= link_to "About", "#", class: "footer-link" %></li>
          <li><%= link_to "Assistance", "#", class: "footer-link" %></li>
          <li><%= link_to "Privacy", "https://ec.europa.eu/info/law/law-topic/data-protection_en", target: "_blank", class: "footer-link" %></li>
          <li><%= link_to "Terms",  "https://www.commissioner.brussels/en/i-am-an-expat/housing/82-housing/104-signing-a-lease", target: "_blank", class: "footer-link" %></li>

        </ul>
        <ul class="footer-list-right">
          <li class="footer-text"><%= DateTime.now.next_year(50).strftime('%A - %d  - %B - %Y') %></li>

        </ul>
      </div>
    </div>

  </body>
</html>

app/views/pages/profile.html.erb
<section id="boat_services" class="my-5">
  <div class="container">
    <div class="profile-page">
      <h2 class="profile-name">PROFILE</h2>
      <p class="ab"><%= link_to "My bookings", my_bookings_spaceships_path, class: "form-link-a" %></p>
      <p class="ab"><%= link_to "My spaceships", my_spaceships_spaceships_path, class: "form-link-a"  %></p>
      <p class="ab"><%= link_to "Change my profile data", edit_user_registration_path, class: "form-link-a"  %></p>
      <p class="ab"><%= link_to "Back to renting", spaceships_path, class: "form-link-a"  %></p>
    </div>
  </div>
</section>

app/views/reservations/show.html.erb
<div class="form-block">
  <div class="left-block">
    <div>
      <p>Have a nice journey with <%=  @spaceship.name %> !</p>
      <p>Here are the details of your reservation:</p>
    </div>
    <div>
      <%= cl_image_tag @spaceship.photo.key, height: 380, width: 400, crop: :fill %>    </div>
    <div class="desc-flex">
      <p id="title"><%=  @spaceship.name %></p>
    </div>
    <div id="description-index">
      <div class="desc-flex">
        <p class="description-list">Capacity:</p>
        <p class="description-text"><%= @spaceship.capacity %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Speed Of Light:</p>
        <p class="description-text"><%= @spaceship.speed_of_light %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Category:</p>
        <p class="description-text"><%= @spaceship.category %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Location:</p>
        <p class="description-text"><%= @spaceship.location %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Brand:</p>
        <p class="description-text"><%= @spaceship.brand %></p>
      </div>
    </div>
  </div>

  <div>
    <div id="price-reviews">
      <p class="description-list">Price per day</p>
      <p id="price"><%= (@spaceship.price).to_s + "㉿" %></p>
    </div>
    <div id="external-fee">
      <div class="price-flex">
        <p class="description-list">Docking Fee</p>
        <p>2000㉿</p>
      </div>
      <div class="price-flex">
        <p class="description-list">Powering Fee</p>
        <p>20000㉿</p>
      </div>
    </div>
    <div id="total">
      <div class="price-flex">
        <p class="description-list">TOTAL</p>
        <p><%= ((((@reservation.end_date - @reservation.start_date).round) * @spaceship.price) + 22000).to_s + "㉿" %></p>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="reservation-form">
  <%= simple_form_for [@spaceship, @reservation] do |f| %>
    <div class="reservation-choice">
      <%= f.input :start_date, label: "From", as: :date, html5: true %>
      <%= f.input :end_date, label: "To", as: :date, html5: true %>
    </div>
    <div class="reservation-submit">
      <%= f.button :submit, "BOOK IT", class: "reserve-button" %>
    </div>
  <% end %>
</div>

app/views/spaceships/_form.html.erb
<%= simple_form_for(@reservation) do |f| %>
  <%= f.input :start_date, label: "From", placeholder: 'yyyy/mm/dd', required: true %>
  <%= f.input :end_date, label: "To", placeholder: 'yyyy/mm/dd', required: true %>
  <%= f.submit %>
<% end %>

app/views/spaceships/edit.html.erb
<<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit a spaceship</h3>
        <%= simple_form_for [@user, @spaceship] do |f| %>
            <%= f.input :name, placeholder: 'Name of the spaceship' %>
            <%= f.label  (capture do %>
                <%= "Category"%>
            <% end) %>
            <%= f.select :category, [["A"], ["B"], ["C"], ["D"], ["E"]] %>
            <%= f.input :location, placeholder: 'Location' %>
            <%= f.input :capacity, placeholder: 'capacity' %>
            <%= f.input :price, placeholder: 'Price' %>
            <%= f.input :photo, as: :file %>
            <%= f.input :description, as: :text, :input_html => { class: 'test', :cols => 5, :rows => 10 } %>
            <%= f.label  (capture do %>
                <%= "Speed of light"%>
            <% end) %>
            <%= f.select :speed_of_light,  [['Yes', true], ['No', false]]%>
            <%= f.input :fuel_drive, placeholder: 'Fuel Drive' %>
            <%= f.input :brand, placeholder: 'Brand' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaceships/index.html.erb
<%#
<span class="center"> Have a nice journey among the stars </span>


<div class = "container"> <h1>lorem<h1><br>
<h1>lorem<h1><br>

<h1>lorem<h1><br> %>

  <section id="boat_services" class="main-container">
    <div class="container">
      <div class="row">
        <% @spaceships.reverse.each do |spaceship| %>

        <div class="col-md-4 card-link">
        <%= link_to spaceship_path(spaceship) do %>
          <figure>
            <% if spaceship.photo.attached? %>
              <%= cl_image_tag(spaceship.photo.key, :width => 460, :height => 380, class:"mb-2")%>
            <% else%>
              <img src="https://loremflickr.com/380/460/spaceships" class="mb-2"alt="">
            <% end%>
            <figcaption class="outside">
              <h2 class="text-black"><span><%=spaceship.name%></span></h2>
            <div class="pricereview">
              <p class="medium text-black mb-0"><%=spaceship.price%>㉿ | day</p>
            </div>
              <p class="text-desc"><%=spaceship.description%></p>
            </figcaption>
          </figure>
        <%end%>
        </div>
      <% end %>
      </div>
    </div>
  </section>

app/views/spaceships/my_bookings.html.erb
<section id="boat_services" class="my-5">
  <div class="container">
    <div class="title-booking">
      <h2 class="booking-title">Your Spaceship</h2>
    </div>
    <div class="row">

            <% @reservations.each do |reservation| %>

      <div class="col-md-4 card-link">
        <figure>
           <% if reservation.spaceship.photo.attached? %>
      <%= cl_image_tag reservation.spaceship.photo.key, height: 380, width: 400, crop: :fill %>
      <% else%>
          <img src="https://loremflickr.com/380/400/spaceships" class="mb-2"alt="">
        <% end%>
          <figcaption class="outside">
            <h2 class="image-title"><span><%=reservation.spaceship.name%></span></h2>
            <p class="small text-black mb-0">Total Price: ㉿ <%= (((reservation.end_date - reservation.start_date).round) * reservation.spaceship.price).to_i%></p>
            <p class="text-desc">Description: <%=reservation.spaceship.description%></p>
            <p class="text-desc">Your Name: <%= reservation.user.first_name %> <%= reservation.user.last_name %></p>
            <p class="text-desc">Number of day(s): <%= (reservation.end_date - reservation.start_date).round %></p>
            <p class="text-desc">From: <%= reservation.start_date%> to: <%= reservation.end_date%></p>
            <%= link_to "Delete", spaceship_reservation_path(reservation.spaceship.id, reservation.id) ,data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
          </figcaption>
        </figure>
      </div>
     <% end %>

    </div>

  </div>
</section>

app/views/spaceships/my_spaceships.html.erb
<section id="boat_services" class="my-5">
  <div class="container">

    <div class="row">
      <% @spaceships.each do |spaceship| %>
        <div class="col-md-4 card-link">
        <%= link_to spaceship_path(spaceship) do %>
          <figure>
            <% if spaceship.photo.attached? %>
              <%= cl_image_tag spaceship.photo.key, height: 380, width: 400, crop: :fill %>
            <% else%>
              <img src="https://loremflickr.com/380/400/spaceships" class="mb-2"alt="">
            <% end%>
            <figcaption class="inside">
              <h2 class="text-black"><span><%=spaceship.name%></span></h2>
            </figcaption>
            <figcaption class="outside">
              <p class="small text-black mb-0">Price:㉿<%=spaceship.price%>|day</p>
              <p class="text-desc">Description:<%=spaceship.description%></p>
              <p class="text-desc">Category:<%=spaceship.category%></p>
              <p class="text-desc">location:<%=spaceship.location%></p>
              <p class="text-desc">Capacity:<%=spaceship.capacity%></p>
              <p class="text-desc">Brand:<%=spaceship.brand%></p>
              <%= link_to "Edit", edit_spaceship_path(spaceship)%> /
              <%= link_to "Delete", spaceship_path(spaceship),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </figcaption>
          </figure>
        <%end%>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/spaceships/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="creation-box">
        <h3 class="new-title">ADD YOUR SPACESHIP</h3>
        <%= simple_form_for [@user, @spaceship] do |f| %>
            <%= f.input :name, placeholder: 'Name of the spaceship', class: "new-text" %>
            <%= f.label  (capture do %>
                <%= "Category"%>
            <% end), class: "new-text" %>
            <%= f.select :category, [["A"], ["B"], ["C"], ["D"], ["E"]], class: "new-text" %>
            <%= f.input :location, placeholder: 'Location', class: "new-text" %>
            <%= f.input :capacity, placeholder: 'capacity', class: "new-text" %>
            <%= f.input :price, placeholder: 'Price', class: "new-text" %>
            <%= f.input :photo, as: :file, class: "new-text" %>
            <%= f.input :description, as: :text, :input_html => { class: 'test', :cols => 5, :rows => 10 }, class: "new-text" %>
            <%= f.label  (capture do %>
                <%= "Speed of light"%>
            <% end), class: "new-text" %>
            <%= f.select :speed_of_light,  [['Yes', true], ['No', false]], class: "new-text"%>
            <%= f.input :fuel_drive, placeholder: 'Fuel Drive', class: "new-text" %>
            <%= f.input :brand, placeholder: 'Brand', class: "new-text" %>
          <%= f.submit class: 'button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaceships/show.html.erb
<div class="form-block">
  <div class="left-block">
    <div>
      <% if @spaceship.photo.attached? %>
      <%= cl_image_tag @spaceship.photo.key, height: 380, width: 400, crop: :fill %>
      <% else%>
          <img src="https://loremflickr.com/380/400/spaceships" class="mb-2"alt="">
        <% end%>
    </div>
    <div class="desc-flex">
      <p id="title"><%=  @spaceship.name %></p>
    </div>
    <div id="description-index">
      <div class="desc-flex">
        <p class="description-list">Capacity:</p>
        <p class="description-text"><%= @spaceship.capacity %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Speed Of Light:</p>
        <p class="description-text"><%= @spaceship.speed_of_light %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Category:</p>
        <p class="description-text"><%= @spaceship.category %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Location:</p>
        <p class="description-text"><%= @spaceship.location %></p>
      </div>
      <div class="desc-flex">
        <p class="description-list">Brand:</p>
        <p class="description-text"><%= @spaceship.brand %></p>
      </div>
    </div>
  </div>
  <div class="form-container">
    <div>
      <div id="infinite-text">
        <p> RESERVATION </p>
      </div>
    <%# <div id="price-reviews">
      <p id="price">17990㉿</p>
      <p>★3.8 | 1001 reviews</p>
    </div> %>
    <%= render 'shared/form'%>
    <%# <%= cl_image_tag("X-wing_2_Fathead_zcfe3q",
          width: 400, height: 300, crop: :fill) %>
    </div>
    <div id="infinite-text">
      <p>To the infinite and beyond...</p>
    </div>
    <div id="external-fee">
      <div class="price-flex">
        <p class="description-list">Docking Fee</p>
        <p>2000㉿</p>
      </div>
      <div class="price-flex">
        <p class="description-list">Powering Fee</p>
        <p>20000㉿</p>
      </div>
    </div>
  </div>
</div>